document.write("<div id = 'ques'> ques<div>")
document.write("<div id = 'Home'> Home<div>")
document.write("		<div id = 'Hot'> Hot<div>")
document.write("		<form id='searchform' action='search.php' method='get'>")
document.write("		<p>")
document.write("		<label for='search'>Search:</label>")
document.write("		<input type='text' id='search' name='search' maxlength='50'>")
document.write("		</p>")
document.write("		<input class='bttn' type='submit' value='Submit'>")
document.write("	</form>		")
document.write("		<a href = 'Login.html'>")
document.write("		<div id = 'LogIn'> Log in<div><!-- todo -->")
document.write("		</a>")
document.write("	<a href = 'Register.html'>")
document.write("		<div id = 'Register'> Register<div>")
document.write("		</a>")

